const fs=require('fs'),vm=require('vm'),path=require('path');
const REPO=path.join(__dirname,'..'); const W=1000,H=1000; let strokes=[];
const ctxMock={strokeStyle:'#000',fillStyle:'#000',lineWidth:1,font:'',textAlign:'center',textBaseline:'middle',_path:[],beginPath(){this._path=[];},moveTo(x,y){this._path.push(['M',x,y]);},lineTo(x,y){this._path.push(['L',x,y]);},quadraticCurveTo(){},rect(){},closePath(){},stroke(){for(let i=1;i<this._path.length;i++){const a=this._path[i-1],b=this._path[i];if(b[0]==='L')strokes.push({x1:Math.round(a[1]),y1:Math.round(a[2]),x2:Math.round(b[1]),y2:Math.round(b[2]),c:(''+this.strokeStyle).toLowerCase()});}},fill(){},clearRect(){strokes=[];},fillText(){},measureText(t){return{width:(t||'').length*8};},save(){},restore(){},setLineDash(){},setTransform(){},arc(){}};
const canvasMock={width:W,height:H,getContext:()=>ctxMock,getBoundingClientRect:()=>({left:0,top:0}),addEventListener:()=>{},style:{}};
const g=()=>({addEventListener:()=>{},classList:{add:()=>{},remove:()=>{},contains:()=>false,toggle:()=>{}},style:{},value:'',querySelector:()=>({value:''}),querySelectorAll:()=>[],appendChild:()=>{},innerHTML:'',textContent:'',dataset:{},rows:[],setAttribute:()=>{},removeAttribute:()=>{},getAttribute:()=>null,hasAttribute:()=>false});
const documentMock={getElementById:(id)=>id==='canvas'?canvasMock:id==='canvas-container'?{offsetWidth:W,offsetHeight:H,addEventListener:()=>{},scrollLeft:0,scrollTop:0}:id==='tabVariabili'?{rows:[]}:g(),addEventListener:()=>{},createElement:()=>g(),querySelector:()=>g(),querySelectorAll:()=>[],body:g(),documentElement:g()};
const ctx={document:documentMock,window:{addEventListener:()=>{},innerWidth:W,innerHeight:H,matchMedia:()=>({matches:false,addEventListener:()=>{}})},localStorage:{getItem:()=>null,setItem:()=>{}},MutationObserver:function(){this.observe=()=>{}},console:{log:()=>{},error:()=>{},warn:()=>{}},Math,JSON,parseInt,parseFloat,isNaN,Set,Array,Object,String,Number,RegExp,Promise,setTimeout,eval,alert:()=>{},confirm:()=>true,location:{}};
vm.createContext(ctx);
for(const n of ['theme','state','utils','variables','layout','rendering','popups','interaction','fileIO','init'])vm.runInContext(fs.readFileSync(REPO+'/js/core/'+n+'.js','utf8'),ctx,{filename:n});
vm.runInContext(fs.readFileSync(REPO+'/js/execute.js','utf8'),ctx,{filename:'execute.js'});
vm.runInContext('window.onload();',ctx);
const run=c=>vm.runInContext(c,ctx);
const ins=(f,t)=>{run(`frecceSelected=frecce.findIndex(ff=>${f});`);run(`inserisciNodo(${JSON.stringify(t)});`);run('draw(nodi);');};
run('draw(nodi);');ins('ff.type==="normal"','while');ins('ff.type==="loop_body"','if');run('draw(nodi);');
console.log('cssVar:', run("cssVar('--exec-edge-color','#ff9800')"));
console.log('typeof highlightExecEdge:', run("typeof highlightExecEdge"));
run("_execBranch='true'; strokes=[]; highlightExecEdge(2,1);");
console.log('executingEdge:', run('JSON.stringify(executingEdge)'));
console.log('strokes total:', strokes.length);
const cnt={}; strokes.forEach(s=>cnt[s.c]=(cnt[s.c]||0)+1);
console.log('colori:', JSON.stringify(cnt));
