const fs=require('fs'),vm=require('vm'),path=require('path');const REPO=path.join(__dirname,'..');const W=1000,H=1000;
const ctxMock={strokeStyle:'#000',fillStyle:'#000',lineWidth:1,font:'',textAlign:'center',textBaseline:'middle',beginPath(){},moveTo(){},lineTo(){},quadraticCurveTo(){},rect(){},closePath(){},stroke(){},fill(){},clearRect(){},fillText(){},measureText(t){return{width:(t||'').length*8};},save(){},restore(){},setLineDash(){},setTransform(){},arc(){}};
const canvasMock={width:W,height:H,getContext:()=>ctxMock,getBoundingClientRect:()=>({left:0,top:0,width:W,height:H}),addEventListener:()=>{},setPointerCapture:()=>{},releasePointerCapture:()=>{},style:{}};
const gg=()=>({addEventListener:()=>{},classList:{add:()=>{},remove:()=>{},contains:()=>false,toggle:()=>{}},style:{},value:'',querySelector:()=>({value:''}),querySelectorAll:()=>[],appendChild:()=>{},innerHTML:'',textContent:'',dataset:{},rows:[],setAttribute:()=>{},removeAttribute:()=>{},getAttribute:()=>null,hasAttribute:()=>false,disabled:false});
const documentMock={getElementById:(id)=>id==='canvas'?canvasMock:id==='canvas-container'?{offsetWidth:W,offsetHeight:H,addEventListener:()=>{},scrollLeft:0,scrollTop:0}:gg(),addEventListener:()=>{},createElement:()=>gg(),querySelector:()=>gg(),querySelectorAll:()=>[],body:gg(),documentElement:gg()};
const ctx={document:documentMock,window:{addEventListener:()=>{},innerWidth:W,innerHeight:H,matchMedia:()=>({matches:false,addEventListener:()=>{}})},localStorage:{getItem:()=>null,setItem:()=>{}},MutationObserver:function(){this.observe=()=>{}},console:{log:function(){},error:function(){},warn:function(){}},Math:Math,JSON:JSON,parseInt:parseInt,parseFloat:parseFloat,isNaN:isNaN,Set:Set,Array:Array,Object:Object,String:String,Number:Number,RegExp:RegExp,Promise:Promise,setTimeout:setTimeout,eval:eval,alert:function(){},confirm:function(){return true;},prompt:function(){return '1';},location:{},matchMedia:function(){return {matches:false};}};
vm.createContext(ctx);for(const n of ['theme','state','utils','variables','layout','rendering','popups','interaction','fileIO','init'])vm.runInContext(fs.readFileSync(REPO+'/js/core/'+n+'.js','utf8'),ctx,{filename:n});vm.runInContext(fs.readFileSync(REPO+'/js/execute.js','utf8'),ctx,{filename:'execute.js'});vm.runInContext('window.onload();',ctx);
const run=c=>vm.runInContext(c,ctx);
run('frecceSelected=frecce.findIndex(function(ff){return ff.type==="normal";}); inserisciNodo("print");');
run('frecceSelected=frecce.findIndex(function(ff){return ff.type==="normal" && ff.fromNodeIndex===1;}); inserisciNodo("print"); calcoloY(nodi); draw(nodi);');
run('flow.nodes[1].info="\\"a\\""; flow.nodes[2].info="\\"b\\"";');
run('globalThis.__seq=[]; var _hn=highlightExecNode; highlightExecNode=function(i){__seq.push("NODO("+i+")"); return _hn.apply(this,arguments);};');
run('runSpeed=350; _runtimeVars=JSON.parse(JSON.stringify(flow.variables||[])); currentNode="2"; prevNode="1"; _bfRunning=false; if(typeof _paused!=="undefined")_paused=true; _execBranch=null; highlightExecEdge(1,2,null); __seq.length=0;');
(async()=>{
 await run('(async()=>{ try{ await executeStep(); }catch(e){globalThis.__err=String(e&&e.stack||e);} })()');
 console.log('PASSO 1 (da pausa-su-arco): seq=', run('JSON.stringify(__seq)'), ' currentNode=', run('String(currentNode)'), ' executingEdge=', run('JSON.stringify(executingEdge)'));
 run('__seq.length=0;');
 await run('(async()=>{ try{ await executeStep(); }catch(e){globalThis.__err=String(e&&e.stack||e);} })()');
 console.log('PASSO 2 (esegue B):        seq=', run('JSON.stringify(__seq)'), ' currentNode=', run('String(currentNode)'));
 console.log('err:', run('globalThis.__err||"nessuno"'));
})();
