const fs=require('fs'),vm=require('vm'),path=require('path');const REPO=path.join(__dirname,'..');const W=1000,H=1000;
const errs=[];
const ctxMock={strokeStyle:'#000',fillStyle:'#000',lineWidth:1,font:'',textAlign:'center',textBaseline:'middle',beginPath(){},moveTo(){},lineTo(){},quadraticCurveTo(){},rect(){},closePath(){},stroke(){},fill(){},clearRect(){},fillText(){},measureText(t){return{width:(t||'').length*8};},save(){},restore(){},setLineDash(){},setTransform(){},arc(){}};
const canvasMock={width:W,height:H,getContext:()=>ctxMock,getBoundingClientRect:()=>({left:0,top:0,width:W,height:H}),addEventListener:()=>{},setPointerCapture:()=>{},releasePointerCapture:()=>{},style:{}};
const consoleOut={appendChild:(el)=>{ if(el&&el.textContent) errs.push(el.textContent); },scrollTop:0,scrollHeight:0,style:{}};
const gg=()=>{const o={appendChild:function(){},addEventListener:()=>{},classList:{add:()=>{},remove:()=>{},contains:()=>false,toggle:()=>{}},style:{},value:'',innerHTML:'',textContent:'',dataset:{},rows:[],cells:[],setAttribute:()=>{},removeAttribute:()=>{},getAttribute:()=>null,hasAttribute:()=>false,disabled:false};o.querySelector=()=>gg();o.querySelectorAll=()=>[];return o;};
const documentMock={getElementById:(id)=>id==='console-output'?consoleOut:id==='canvas'?canvasMock:gg(),addEventListener:()=>{},createElement:()=>gg(),querySelector:()=>gg(),querySelectorAll:()=>[],body:gg(),documentElement:gg()};
const ctx={document:documentMock,window:{addEventListener:()=>{},innerWidth:W,innerHeight:H,matchMedia:()=>({matches:false,addEventListener:()=>{}})},localStorage:{getItem:()=>null,setItem:()=>{}},MutationObserver:function(){this.observe=()=>{}},console:{log:function(){},error:function(){},warn:function(){}},Math:Math,JSON:JSON,parseInt:parseInt,parseFloat:parseFloat,isNaN:isNaN,Set:Set,Array:Array,Object:Object,String:String,Number:Number,RegExp:RegExp,Promise:Promise,setTimeout:setTimeout,eval:eval,alert:function(){},confirm:function(){return true;},prompt:function(){return '9';},location:{},matchMedia:function(){return {matches:false};},errMsg:function(k,p){return k+' '+JSON.stringify(p||{});},i18nText:function(){return null;},i18nFormat:function(){return null;}};
vm.createContext(ctx);for(const n of ['theme','state','utils','variables','layout','rendering','popups','interaction','fileIO','init'])vm.runInContext(fs.readFileSync(REPO+'/js/core/'+n+'.js','utf8'),ctx,{filename:n});vm.runInContext(fs.readFileSync(REPO+'/js/execute.js','utf8'),ctx,{filename:'execute.js'});vm.runInContext('window.onload();',ctx);
const run=c=>vm.runInContext(c,ctx);
run('try{printMessage=function(){};}catch(e){}');
const call=async(info)=>{ errs.length=0; return await run('(async()=>{try{return await executeNode({type:"assign",info:'+JSON.stringify(info)+',next:"2"},"1",__V,null);}catch(e){return "THROW:"+(e&&e.message);}})()'); };
run('executingNodeIndex=-1; currentNode="1";');
run('globalThis.__V=[{name:"x",type:"int",value:0,uninit:true},{name:"y",type:"int",value:0}];');
(async()=>{
 const r1=await call("y = x + 1");
 console.log('1) y=x+1 (x UNINIT): ret='+JSON.stringify(r1)+'  err='+JSON.stringify(errs)+'  y='+run('__V.find(v=>v.name==="y").value')+'  [atteso: err_uninit_var, y=0]');
 const r2=await call("x = 5");
 console.log('2) x=5 (scrittura):  ret='+JSON.stringify(r2)+'  x='+run('JSON.stringify(__V.find(v=>v.name==="x"))')+'  [atteso: value 5, uninit via]');
 const r3=await call("y = x + 1");
 console.log('3) y=x+1 (x INIT):   ret='+JSON.stringify(r3)+'  err='+JSON.stringify(errs)+'  y='+run('__V.find(v=>v.name==="y").value')+'  [atteso: nessun err, y=6]');
})().catch(e=>console.log('OUTER',e&&e.message));
