const fs=require('fs'),vm=require('vm'),path=require('path');const REPO=path.join(__dirname,'..');const W=1000,H=1000;
const ctxMock={strokeStyle:'#000',fillStyle:'#000',lineWidth:1,font:'',textAlign:'center',textBaseline:'middle',beginPath(){},moveTo(){},lineTo(){},quadraticCurveTo(){},rect(){},closePath(){},stroke(){},fill(){},clearRect(){},fillText(){},measureText(t){return{width:(t||'').length*8};},save(){},restore(){},setLineDash(){},setTransform(){},arc(){}};
const canvasMock={width:W,height:H,getContext:()=>ctxMock,getBoundingClientRect:()=>({left:0,top:0}),addEventListener:()=>{},style:{}};
function E(){return new Proxy({addEventListener(){},removeEventListener(){},classList:{add(){},remove(){},contains(){return false},toggle(){}},style:{},value:'',querySelector(){return E()},querySelectorAll(){return []},appendChild(){},removeChild(){},insertBefore(){},innerHTML:'',textContent:'',dataset:{},rows:[],cells:[],disabled:false,checked:false,setAttribute(){},removeAttribute(){},getAttribute(){return null},hasAttribute(){return false},parentNode:null,focus(){},blur(){},click(){},getContext:()=>ctxMock,width:W,height:H,offsetWidth:W,offsetHeight:H,scrollLeft:0,scrollTop:0,getBoundingClientRect:()=>({left:0,top:0,width:W,height:H})},{get(t,p){return p in t?t[p]:E()}});}
const documentMock={getElementById:(id)=>id==='canvas'?canvasMock:E(),addEventListener(){},createElement:()=>E(),querySelector:()=>E(),querySelectorAll:()=>[],body:E(),documentElement:E()};
const LOG=[];
const ctx={document:documentMock,window:{addEventListener(){},innerWidth:W,innerHeight:H,matchMedia:()=>({matches:false,addEventListener(){}})},localStorage:{getItem:()=>null,setItem(){}},MutationObserver:function(){this.observe=()=>{}},console:{log(){},error(){},warn(){}},Math,JSON,parseInt,parseFloat,isNaN,Set,Array,Object,String,Number,RegExp,Promise,setTimeout,eval,alert(){},confirm:()=>true,location:{},errMsg:k=>k,Proxy};
vm.createContext(ctx);for(const n of ['theme','state','utils','variables','layout','rendering','popups','interaction','fileIO','init'])vm.runInContext(fs.readFileSync(REPO+'/js/core/'+n+'.js','utf8'),ctx,{filename:n});vm.runInContext(fs.readFileSync(REPO+'/js/execute.js','utf8'),ctx,{filename:'execute.js'});vm.runInContext('window.onload();',ctx);
const run=c=>vm.runInContext(c,ctx);const ins=(f,t)=>{run(`frecceSelected=frecce.findIndex(ff=>${f});`);run(`inserisciNodo(${JSON.stringify(t)});`);run('draw(nodi);');};
run('draw(nodi);');ins('ff.type==="normal"','do');ins('ff.type==="loop_body"','print'); run('flow.nodes[1].info="true"; draw(nodi);');
ctx._LOG=LOG;run('sleep=function(){return Promise.resolve();};');
run('var _hn=highlightExecNode; highlightExecNode=function(i){ if(i>=0)_LOG.push("ESAGONO/nodo("+i+")"); return _hn(i); };');
run('var _ae=animateExecEdge; animateExecEdge=async function(f,t,dt){ var sr=!_isFirstVisitDo(f,prevNode); var grp=computeEdgeGroups(f,t,_execBranch,sr); grp.forEach(x=>_LOG.push("arco["+x.type+"]")); return _ae(f,t,1); };');
(async()=>{ for(let s=0;s<7;s++){ try{ await run('executeStep()'); }catch(e){ LOG.push("(stop:"+e.message.slice(0,30)+")"); break; } } console.log(LOG.join(" -> ")); })().catch(e=>console.log(LOG.join(" -> ")+" ERR"));
